server {
    listen 443 ssl;
    server_name aakroud.42.fr;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLDv1.2 TLDv1.3;
    #still need more config
}